name: Release Juzgadores 2024-2025 data

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Generate files
        run: |
          python -m dof_utils.extract_juzgadores data/15122024-MAT.pdf ./output

      - name: Upload Release Assets
        run: |
          tar -czf datos.tar.gz -C output .
          gh release upload ${{ github.event.release.tag_name }} datos.tar.gz --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
